name: 构建并发布Docker镜像V3

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 必须是 write，才能创建 Release
      packages: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 设置QEMU
        uses: docker/setup-qemu-action@v3

      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: 登录到GitHub容器注册表
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER }}

      - name: 提取Docker元数据
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/pansou
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      - name: 安装 Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23' # 与 Dockerfile 保持一致

      # 分别编译两个架构的可执行文件
      - name: 编译 amd64 版本
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/pansou_amd64 .

      - name: 编译 arm64 版本
        run: |
          GOOS=linux GOARCH=arm64 go build -o dist/pansou_arm64 .

      - name: 上传 dist 目录
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist/

      - name: 构建并推送Docker镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ github.event.repository.updated_at }}
            VCS_REF=${{ github.sha }}
            VERSION=${{ steps.meta.outputs.version }}

      # --- 新增：生成日期型 tag_name 和 zip_name ---
      - name: 生成日期型 tag_name 和 zip_name
        run: |
          echo "TAG_NAME=release-$(date +%Y%m%d)" >> $GITHUB_ENV
          echo "ZIP_NAME=pansou_$(date +%Y%m%d).zip" >> $GITHUB_ENV

      # 压缩两个平台的可执行文件
      - name: 打包两个平台文件带日期
        run: |
          cd dist
          zip "${ZIP_NAME}" pansou_amd64 pansou_arm64

      - name: 发布到 GitHub Release
        uses: softprops/action-gh-release@v1
        if: github.event_name != 'pull_request'
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: "Release ${{ env.TAG_NAME }}"
          body: "自动发布：包含当天编译的 pansou_amd64 和 pansou_arm64 文件"
          files: dist/${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
